import cv2
import matplotlib.pyplot as plt
from HighlightImage import HighlightImage

highlight = HighlightImage("plantioCana.jpg")
sourceImg = highlight.getSourceImg()
editedImg = highlight.editImage()
lowPassImg = highlight.applyMedianFilter(editedImg, 7)

# Passa alta canny
cannyImg = highlight.applyCannyFilter(lowPassImg, 0, 0)
plt.figure(figsize=(10,4))
plt.subplot(121)
plt.imshow(sourceImg[...,::-1])
plt.title('Original') 
plt.axis("off")
plt.subplot(122)
plt.imshow(cannyImg, cmap='gray')
plt.title('Canny') 
plt.axis("off")
plt.show()
cv2.waitKey(0)

# Passa alta Roberts
robertsImg = highlight.applyRobertsFilter(lowPassImg)
plt.figure(figsize=(10,4))
plt.subplot(121)
plt.imshow(sourceImg[...,::-1])
plt.title('Original') 
plt.axis("off")
plt.subplot(122)
plt.imshow(robertsImg, cmap='gray')
plt.title('Roberts') 
plt.axis("off")
plt.show()
cv2.waitKey(0)

# Passa alta Sobel
filteredImgX = highlight.applySobelFilter(lowPassImg, 1, 0, 3)
filteredImgY = highlight.applySobelFilter(lowPassImg, 0, 1, 3)
filteredImgXY = highlight.applySobelFilter(lowPassImg, 1, 1, 3)
plt.figure(figsize=(10,4))
plt.subplot(221)
plt.imshow(sourceImg[...,::-1])
plt.title('Original') 
plt.axis("off")
plt.subplot(222)
plt.imshow(filteredImgX, cmap='gray')
plt.title('Sobel X') 
plt.axis("off")
plt.subplot(223)
plt.imshow(filteredImgY, cmap='gray')
plt.title('Sobel Y') 
plt.axis("off")
plt.subplot(224)
plt.imshow(filteredImgXY, cmap='gray')
plt.title('Sobel XY')
plt.axis("off")
plt.show()
cv2.waitKey(0)
cv2.destroyAllWindows()

# Passa alta Prewitt
prewittImg = highlight.applyPrewittFilter(lowPassImg)
plt.figure(figsize=(10,4))
plt.subplot(121)
plt.imshow(sourceImg[...,::-1])
plt.title('Original') 
plt.axis("off")
plt.subplot(122)
plt.imshow(prewittImg, cmap='gray')
plt.title('Prewitt') 
plt.axis("off")
plt.show()
cv2.waitKey(0)